name: 'upload-file-to-supabase-storage'
description: 'Upload local file to Supabase Storage'
author: 'StatusBase by Zernonia'
branding:
  icon: 'image'
  color: 'blue'

inputs:
  bucket:
    required: true
    description: 'Name of the bucket to upload to'
    default: ''

outputs:
  result:
    description: 'Media Key for the image'

runs:
  using: 'node16'
  main: 'dist/index.js'
