name: 'Upload file to Supabase Storage'
description: 'Upload file to Supabase Storage with GitHub Actions'
author: 'Datapods by JEndler'
branding:
  icon: 'server'
  color: 'purple'

inputs:
  path:
    required: true
    description: 'Path name of the file or folder to be uploaded (eg: /screenshots.png, /assets)'
  bucket:
    required: true
    description: 'Name of the bucket to upload to'
    default: ''
  subfolder:
    required: false
    description: 'Subfolder in the Supabase Bucket to upload into'
    default: 'static'
  cache_control:
    required: true
    description: 'Cache-control: max-age=<seconds>'
    default: '3600'
  upsert:
    required: true
    description: 'Replace the file with the same name or not'
    default: 'false'

outputs:
  url:
    description: 'URL of the uploaded file, if bucket is public'

runs:
  using: 'node20'
  main: 'dist/index.js'
